name: LineageOS Hetzner Build
description: Run the LineageOS Hetzner build tool as a composite action step.
inputs:
  HETZNER_TOKEN:
    description: Hetzner Cloud API Token
    required: true
  HETZNER_SERVER_TYPE:
    description: Hetzner server type
    required: false
  HETZNER_SERVER_LOCATION:
    description: Hetzner server location
    required: false
  HETZNER_SERVER_IMAGE:
    description: Hetzner server image
    required: false
  BUILD_COMPOSE_FILE:
    description: docker-compose file path
    required: false
  BUILD_SERVICE_NAME:
    description: docker-compose service name to run
    required: false
  BUILD_SOURCE_DIR:
    description: Local source directory that contains docker-compose file and dependencies
    required: true
  ARTIFACT_DIR:
    description: Remote artifact directory
    required: false
  ARTIFACT_PATTERN:
    description: Artifact file glob
    required: false
  KEEP_SERVER_ON_FAILURE:
    description: Keep server alive on failure for debugging
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - name: Compile builder
      shell: bash
      working-directory: ${{ github.action_path }}
      run: go build -o lineage-builder ./cmd/lineage-builder
    - name: Run builder
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        HETZNER_TOKEN: ${{ inputs.HETZNER_TOKEN }}
        HETZNER_SERVER_TYPE: ${{ inputs.HETZNER_SERVER_TYPE }}
        HETZNER_SERVER_LOCATION: ${{ inputs.HETZNER_SERVER_LOCATION }}
        HETZNER_SERVER_IMAGE: ${{ inputs.HETZNER_SERVER_IMAGE }}
        BUILD_SOURCE_DIR: ${{ inputs.BUILD_SOURCE_DIR }}
        BUILD_COMPOSE_FILE: ${{ inputs.BUILD_COMPOSE_FILE }}
        BUILD_SERVICE_NAME: ${{ inputs.BUILD_SERVICE_NAME }}
        BUILD_WORKDIR: ${{ inputs.BUILD_WORKDIR }}
        ARTIFACT_DIR: ${{ inputs.ARTIFACT_DIR }}
        ARTIFACT_PATTERN: ${{ inputs.ARTIFACT_PATTERN }}
        KEEP_SERVER_ON_FAILURE: ${{ inputs.KEEP_SERVER_ON_FAILURE }}
      run: ${{ github.action_path }}/lineage-builder
    - name: Cleanup server resources
      if: always()
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        HETZNER_TOKEN: ${{ inputs.HETZNER_TOKEN }}
        KEEP_SERVER_ON_FAILURE: ${{ inputs.KEEP_SERVER_ON_FAILURE }}
      run: |
        # Only run cleanup if KEEP_SERVER_ON_FAILURE is not true
        if [ "$KEEP_SERVER_ON_FAILURE" != "true" ]; then
          ${{ github.action_path }}/lineage-builder --cleanup || true
        fi
